import { 
  CheckSquare, 
  BarChart3, 
  FileText, 
  Calendar, 
  Activity, 
  ListChecks,
  Receipt,
  FileEdit,
  Zap,
  AlertTriangle,
  Sparkles,
  Hammer,
  Inbox,
  Newspaper,
  Wallet,
  TrendingUp,
  GanttChart,
  FolderOpen,
  StickyNote,
  MailCheck,
  Pin,
} from "lucide-react";
import { WidgetDefinition } from "@/types/widgets";
import TasksWidget from "./TasksWidget";
import MetricsWidget from "./MetricsWidget";
import NotesWidget from "./NotesWidget";
import ScheduleWidget from "./ScheduleWidget";
import ActivityWidget from "./ActivityWidget";
import ChecklistWidget from "./ChecklistWidget";
import BillsSummaryWidget from "./BillsSummaryWidget";
import VariationsSummaryWidget from "./VariationsSummaryWidget";
import InvoicesSummaryWidget from "./InvoicesSummaryWidget";
import QuickActionsWidget from "./QuickActionsWidget";
import AlertsWidget from "./AlertsWidget";
import AISummaryWidget from "./AISummaryWidget";
import SubcontractorsWidget from "./SubcontractorsWidget";
import OpenItemsWidget from "./OpenItemsWidget";
import RecentActivityFeedWidget from "./RecentActivityFeedWidget";
import ProjectBudgetVsActualWidget from "./ProjectBudgetVsActualWidget";
import ProjectCashFlowWidget from "./ProjectCashFlowWidget";
import ClientActivityWidget from "./ClientActivityWidget";
import ProgrammeScheduleWidget from "./ProgrammeScheduleWidget";
import ProjectDocumentsWidget from "./ProjectDocumentsWidget";
import QuickNotesWidget from "./QuickNotesWidget";
import PinnedItemsWidget from "./PinnedItemsWidget";

export const widgetRegistry: Record<string, WidgetDefinition> = {
  tasks: {
    type: "tasks",
    name: "Tasks",
    description: "Show upcoming project tasks and assignments",
    icon: CheckSquare,
    component: TasksWidget,
    defaultSize: "md",
    configurable: true,
  },
  metrics: {
    type: "metrics", 
    name: "Project Metrics",
    description: "Display project budget, timeline, and completion metrics",
    icon: BarChart3,
    component: MetricsWidget,
    defaultSize: "lg",
    configurable: true,
  },
  notes: {
    type: "notes",
    name: "Project Notes",
    description: "Quick notes and project updates",
    icon: FileText,
    component: NotesWidget,
    defaultSize: "md",
    configurable: true,
  },
  schedule: {
    type: "schedule",
    name: "Schedule",
    description: "Upcoming scheduled events and milestones",
    icon: Calendar,
    component: ScheduleWidget,
    defaultSize: "md",
    configurable: true,
  },
  activity: {
    type: "activity",
    name: "Activity Feed",
    description: "Recent project activity and updates",
    icon: Activity,
    component: ActivityWidget,
    defaultSize: "md",
    configurable: false,
  },
  checklist: {
    type: "checklist",
    name: "Checklists",
    description: "View and access project checklists",
    icon: ListChecks,
    component: ChecklistWidget,
    defaultSize: "md",
    configurable: true,
  },
  bills: {
    type: "bills",
    name: "Bills Summary",
    description: "Overview of project bills with status breakdown and totals",
    icon: Receipt,
    component: BillsSummaryWidget,
    defaultSize: "md",
    configurable: false,
  },
  variations: {
    type: "variations",
    name: "Variations Summary",
    description: "Track change orders and their impact on project value",
    icon: FileEdit,
    component: VariationsSummaryWidget,
    defaultSize: "md",
    configurable: false,
  },
  invoices: {
    type: "invoices",
    name: "Invoices Summary",
    description: "Client invoicing status and collection tracking",
    icon: FileText,
    component: InvoicesSummaryWidget,
    defaultSize: "md",
    configurable: true,
  },
  quickActions: {
    type: "quickActions",
    name: "Quick Actions",
    description: "One-click buttons for common project tasks",
    icon: Zap,
    component: QuickActionsWidget,
    defaultSize: "md",
    configurable: true,
  },
  alerts: {
    type: "alerts",
    name: "Alerts & Warnings",
    description: "Overdue items, budget warnings, and action items",
    icon: AlertTriangle,
    component: AlertsWidget,
    defaultSize: "md",
    configurable: false,
  },
  aiSummary: {
    type: "aiSummary",
    name: "AI Daily Summary",
    description: "AI-powered briefing of today's schedule, action items, and potential issues",
    icon: Sparkles,
    component: AISummaryWidget,
    defaultSize: "md",
    configurable: false,
  },
  subcontractors: {
    type: "subcontractors",
    name: "Subcontractors",
    description: "Trade contacts assigned to this project with click-to-call",
    icon: Hammer,
    component: SubcontractorsWidget,
    defaultSize: "md",
    configurable: true,
    accent: "teal",
    defaultColumns: 3,
    defaultRowSpan: 3,
  },
  openItems: {
    type: "openItems",
    name: "Open Items",
    description: "Counts of open tasks, defects, pending variations, and RFIs",
    icon: Inbox,
    component: OpenItemsWidget,
    defaultSize: "md",
    configurable: false,
    accent: "amber",
    defaultColumns: 3,
    defaultRowSpan: 2,
  },
  recentActivityFeed: {
    type: "recentActivityFeed",
    name: "Recent Activity Feed",
    description: "Latest activity across the project at a glance",
    icon: Newspaper,
    component: RecentActivityFeedWidget,
    defaultSize: "md",
    configurable: true,
    accent: "purple",
    defaultColumns: 3,
    defaultRowSpan: 3,
  },
  budgetVsActual: {
    type: "budgetVsActual",
    name: "Budget vs Actual",
    description: "Spend vs budget with a progress or bullet bar, plus an optional build-progress bar",
    icon: BarChart3,
    component: ProjectBudgetVsActualWidget,
    defaultSize: "md",
    configurable: true,
    accent: "financial",
    financialGated: true,
    requiredPermission: { key: "financial.budget_actuals", action: "view" },
    defaultColumns: 3,
    defaultRowSpan: 2,
  },
  projectCashFlow: {
    type: "projectCashFlow",
    name: "Project Cash Flow",
    description: "Money in vs money out for this project with weekly confirmation",
    icon: Wallet,
    component: ProjectCashFlowWidget,
    defaultSize: "md",
    configurable: true,
    accent: "green",
    financialGated: true,
    requiredPermission: { key: "dashboard.financial", action: "view" },
    defaultColumns: 3,
    defaultRowSpan: 2,
  },
  clientActivity: {
    type: "clientActivity",
    name: "Client Activity",
    description: "Client-portal events: invoices, proposals, variations sent and accepted",
    icon: MailCheck,
    component: ClientActivityWidget,
    defaultSize: "md",
    configurable: true,
    accent: "purple",
    defaultColumns: 3,
    defaultRowSpan: 3,
  },
  programme: {
    type: "programme",
    name: "Schedule",
    description: "Schedule items and tasks in week or Gantt view",
    icon: GanttChart,
    component: ProgrammeScheduleWidget,
    defaultSize: "lg",
    configurable: true,
    accent: "schedule",
    defaultColumns: 4,
    defaultRowSpan: 3,
  },
  documents: {
    type: "documents",
    name: "Project Documents",
    description: "Files in the linked Google Drive folder for this project",
    icon: FolderOpen,
    component: ProjectDocumentsWidget,
    defaultSize: "md",
    configurable: true,
    accent: "purple",
    defaultColumns: 3,
    defaultRowSpan: 3,
  },
  quickNotes: {
    type: "quickNotes",
    name: "Quick Notes",
    description: "Notion-like quick blocks: heading, text, bullet, and to-do",
    icon: StickyNote,
    component: QuickNotesWidget,
    defaultSize: "md",
    configurable: false,
    accent: "amber",
    defaultColumns: 3,
    defaultRowSpan: 4,
  },
  pinnedItems: {
    type: "pinnedItems",
    name: "Pinned Items",
    description: "Quick access to items you've pinned from across this project",
    icon: Pin,
    component: PinnedItemsWidget,
    defaultSize: "md",
    configurable: true,
    accent: "purple",
    defaultColumns: 3,
    defaultRowSpan: 3,
  },
};

export const getWidgetDefinition = (type: string): WidgetDefinition | undefined => {
  return widgetRegistry[type];
};
